version: '3'

services:
  postgres:
    build: postgres-plpython
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    env_file: .env
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8000 --workers=4 project.wsgi
    volumes:
      - .:/opt/project
    ports:
      - "8000:8000"
      - "8080:8080"
    depends_on:
      - postgres
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
      - POSTGRES_HOST=postgres

volumes:
  postgres_data: